# Package Overview
package_name: classification_model

# Data Files
training_data_file: train.csv
test_data_file: test.csv

# Variables
# The variable we are attempting to predict (sale price)
target: Survived

pipeline_name: classification_model
pipeline_save_file: classification_model_output_v

# Will cause syntax errors since they begin with numbers
# nested dictionary
#Old_Name : New_Name
#variables_to_rename:
#  1stFlrSF: FirstFlrSF
#  2ndFlrSF: SecondFlrSF
#  3SsnPorch: ThreeSsnPortch 

# Intendention matters in yml and here a key with intended dash is the list 
features:
  - PassengerId
  - Pclass
  - Name
  - Sex
  - Age
  - SibSp
  - Parch
  - Ticket
  - Fare
  - Cabin
  - Embarked

  # this one is only to calculate temporal variable:
  #- YrSold

# set train/test split
test_size: 0.1

# to set the random seed
random_state: 2

alpha: 0.001

# categorical variables with NA in train set
categorical_vars_with_na_frequent:
  - Cabin
  #- BsmtQual
  #- BsmtExposure
  #- BsmtFinType1
  #- GarageFinish

#categorical_vars_with_na_missing:
# - Sex
# - Embarked

numerical_vars_with_na:
  - Fare
  - Age




# variables to log transform
numericals_log_vars:
  - Fare
  - Age
  - SibSp

binarize_vars:
  - ScreenPorch

# variables to map
gender_vars:
  - Sex

categorical_vars:
  - Cabin
  - Embarked
  

# variable mappings
#If you want to convert categorical value to Numerical value we use this mapping. Unioun of all categorical values 
#mentioned in the quals_vars and put them in qual_mappings with numeric values.
gender_mappings:
  male: 0
  female: 1




